### PR TITLE
D435i Drivers

### PR DESCRIPTION
**Pull request by Latitude9527**
# D435i Drivers

## Description

This file is a node created based on the Dora platform. It calls the D435i camera to obtain color, depth, left and right infrared data streams, IMU data, and camera extrinsic data. The code will be published within the Dora platform. For installation instructions of Dora, please refer to: https://dora.carsmos.ai/docs/guides/Installation/installing/

### Installation

```pip install -r requirements.txt ### 运行之前请确保已经安装了python3.7以上的版本```

Ex:
- Dora 0.2.3

- D435i SDK ,please refer to:https://github.com/IntelRealSense/librealsense

- python 3.7+

### Launch Step

```dora up```

```dora start example/webcam_color.yaml```

### Output

You will see a window displaying real-time captured color images from the camera.

List any references that might be useful:

- https://dora.carsmos.ai/docs/guides/Installation/installing/
- https://github.com/IntelRealSense

## Pull Request TODO: 

- [ ] Create a new folder for each new hardware under the right categorisation.
- [ ] Add this README template into the folder as well as the source code.

### CODE REVIEW

**Comment by haixuanTao** [comment]
Could it be possible to regroup all the webcam operators into a single operator that can be configurable to output one or multiple outputs at the same time?

Thanks

**Comment by Latitude9527** [comment]
> 

of course，i will modify it

**Comment by Latitude9527** [comment]
> Could it be possible to regroup all the webcam operators into a single operator that can be configurable to output one or multiple outputs at the same time?
> 
> Thanks
I've uploaded the changed code and have verified that it works.If you have time, you can take a look.
Thanks

**Comment by haixuanTao** [comment]
Can we also regroup the plot into a single plot that can manage all input format? Thanks!

**Comment by Latitude9527** [comment]
> Can we also regroup the plot operators into a single plot operator that can manage all input format and can plot one or multiple plot window on the same operator? Thanks!

Do you mean to output the subscribed data stream after running the program, then input the required data stream in cmd and visualize it？

**Comment by haixuanTao** [comment]
So we currently have several plot operators: `plot_depth.py`, `plot_color.py`... to plot the image input within the dataflow. 

Can we have a single operator like `plot_D435i` that can plot one or multiple video stream?

**Pull request merged**
